spring.application.name=loan-management-system-spring-boot-server

spring.datasource.url=jdbc:postgresql://localhost:5432/loan_management_db
spring.datasource.username=postgres
spring.datasource.password=milka
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.main.web-application-type=none