spring.application.name=loan-management-system-spring-boot-server

spring.datasource.url=jdbc:postgresql://localhost:5432/loan_management_db
spring.datasource.username=postgres
spring.datasource.password=milka
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.main.web-application-type=none

# Mail settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=solomonbakkamwesigwa@gmail.com
spring.mail.password=pgzj rche prkv slno
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
