spring.application.name=loan-management-system-spring-boot-server
spring.application.version=v1.0.0

spring.datasource.url=jdbc:h2:file:~/loan_db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.sql.init.mode=embedded

spring.main.web-application-type=none

# Mail settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=solomonbakkamwesigwa@gmail.com
spring.mail.password=pgzj rche prkv slno
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
